server:
  port: 7071
eureka:
  instance:
    hostname: localhost2
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost1:7070/eureka,http://localhost3:7072/eureka
