server:
  port: 7070
eureka:
  instance:
    hostname: localhost1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone:  http://localhost2:7071/eureka,http://localhost3:7072/eureka
